# Generated by Django 4.1.5 on 2023-02-06 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_remove_noticia_foto_noticia_foto1_noticia_foto2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='foto1',
            field=models.ImageField(blank=True, null=True, upload_to='foto1'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='foto2',
            field=models.ImageField(blank=True, null=True, upload_to='foto2'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='foto3',
            field=models.ImageField(blank=True, null=True, upload_to='foto3'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='foto4',
            field=models.ImageField(blank=True, null=True, upload_to='foto4'),
        ),
    ]
