# Generated by Django 4.1.5 on 2023-02-08 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_noticia_foto1_alter_noticia_foto2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noticia',
            old_name='imagen',
            new_name='img1',
        ),
        migrations.RenameField(
            model_name='noticia',
            old_name='foto1',
            new_name='img2',
        ),
        migrations.RenameField(
            model_name='noticia',
            old_name='foto2',
            new_name='img3',
        ),
        migrations.RenameField(
            model_name='noticia',
            old_name='foto3',
            new_name='img4',
        ),
        migrations.RenameField(
            model_name='noticia',
            old_name='foto4',
            new_name='img5',
        ),
    ]
