# Generated by Django 4.1.5 on 2023-02-16 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_product', models.CharField(max_length=200)),
                ('description_product', models.TextField()),
                ('pub_date_product', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
