# Generated by Django 4.1.5 on 2023-02-16 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo_prodcut',
            field=models.ImageField(null=True, upload_to='imagen'),
        ),
    ]
