# Generated by Django 4.1.5 on 2023-02-16 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_product_photo_prodcut'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='photo_prodcut',
            new_name='photo_product',
        ),
    ]
